DOCKERCOMPOSE := docker compose -f docker-compose.yml

DOCKERCOMPOSEEXPLORERBACKEND := backend
DOCKERCOMPOSEEXPLORERBACKENDDB := backend-db
DOCKERCOMPOSEEXPLORERFRONTEND := frontend
DOCKERCOMPOSEEXPLORERPROXY := proxy
DOCKERCOMPOSEEXPLORERSMARTCONTRACTVERIFIER := smart-contract-verifier
DOCKERCOMPOSEEXPLORERVISUALIZER := visualizer
DOCKERCOMPOSEEXPLORERSIGPROVIDER := sig-provider
DOCKERCOMPOSEEXPLORERVISUALIZERPROXY := visualizer-proxy
DOCKERCOMPOSEEXPLORERSTATSDBL2 := stats-db
DOCKERCOMPOSEEXPLORERSTATSL2 := stats

RUNEXPLORERBACKEND := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEXPLORERBACKEND)
RUNEXPLORERBACKENDDB := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEXPLORERBACKENDDB)
RUNEXPLORERFRONTEND := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEXPLORERFRONTEND)
RUNEXPLORERPROXY := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEXPLORERPROXY)
RUNEXPLORERSMARTCONTRACTVERIFIER := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEXPLORERSMARTCONTRACTVERIFIER)
RUNEXPLORERVISUALIZER := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEXPLORERVISUALIZER)
RUNEXPLORERSIGPROVIDER := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEXPLORERSIGPROVIDER)
RUNEXPLORERVISUALIZERPROXY := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEXPLORERVISUALIZERPROXY)
RUNEXPLORERSTATSDBL2 := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEXPLORERSTATSDBL2)
RUNEXPLORERSTATSL2 := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEXPLORERSTATSL2)

STOPEXPLORERBACKEND := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSEEXPLORERBACKEND) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSEEXPLORERBACKEND)
STOPEXPLORERBACKENDDB := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSEEXPLORERBACKENDDB) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSEEXPLORERBACKENDDB)
STOPEXPLORERFRONTEND := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSEEXPLORERFRONTEND) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSEEXPLORERFRONTEND)
STOPEXPLORERPROXY := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSEEXPLORERPROXY) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSEEXPLORERPROXY)
STOPEXPLORERSMARTCONTRACTVERIFIER := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSEEXPLORERSMARTCONTRACTVERIFIER) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSEEXPLORERSMARTCONTRACTVERIFIER)
STOPEXPLORERVISUALIZER := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSEEXPLORERVISUALIZER) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSEEXPLORERVISUALIZER)
STOPEXPLORERSIGPROVIDER := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSEEXPLORERSIGPROVIDER) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSEEXPLORERSIGPROVIDER)
STOPEXPLORERVISUALIZERPROXY := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSEEXPLORERVISUALIZERPROXY) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSEEXPLORERVISUALIZERPROXY)
STOPEXPLORERSTATSDBL2 := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSEEXPLORERSTATSDBL2) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSEEXPLORERSTATSDBL2)
STOPEXPLORERSTATSL2 := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSEEXPLORERSTATSL2) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSEEXPLORERSTATSL2)

.PHONY: run-explorer
run-explorer: ## Runs all explorer services
	$(RUNEXPLORERBACKENDDB)
	$(RUNEXPLORERSTATSDBL2)
	sleep 5
	$(RUNEXPLORERBACKEND)
	$(RUNEXPLORERFRONTEND)
	$(RUNEXPLORERSTATSL2)
	$(RUNEXPLORERSMARTCONTRACTVERIFIER)
	$(RUNEXPLORERVISUALIZER)
	$(RUNEXPLORERSIGPROVIDER)
	$(RUNEXPLORERVISUALIZERPROXY)
	$(RUNEXPLORERPROXY)

.PHONY: stop-explorer
stop-explorer: ## Stops all explorer services
	$(STOPEXPLORERPROXY)
	$(STOPEXPLORERVISUALIZERPROXY)
	$(STOPEXPLORERSIGPROVIDER)
	$(STOPEXPLORERVISUALIZER)
	$(STOPEXPLORERSMARTCONTRACTVERIFIER)
	$(STOPEXPLORERSTATSL2)
	$(STOPEXPLORERFRONTEND)
	$(STOPEXPLORERBACKEND)
	$(STOPEXPLORERSTATSDBL2)
	$(STOPEXPLORERBACKENDDB)

.PHONY: run-explorer-db
run-explorer-db: ## Runs the explorer databases
	$(RUNEXPLORERBACKENDDB)
	$(RUNEXPLORERSTATSDBL2)

.PHONY: stop-explorer-db
stop-explorer-db: ## Stops the explorer databases
	$(STOPEXPLORERSTATSDBL2)
	$(STOPEXPLORERBACKENDDB)

.PHONY: ps
ps: ## Check all running services
	$(DOCKERCOMPOSE) ps --status running --format "table {{.Service}}\t{{.Image}}\t{{.Status}}"

.PHONY: ps-exited
ps-exited: ## Check all exited services
	$(DOCKERCOMPOSE) ps -a --format "table {{.Service}}\t{{.Image}}\t{{.Status}}" \
		| grep 'Exited' \
		|| echo "No exited containers"

.PHONY: help
help: ## Prints this help
		@grep -h -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| sort \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

.DEFAULT_GOAL := help