DOCKERCOMPOSE := docker compose -f docker-compose.yml

DOCKERCOMPOSEEXPLORERBACKEND := backend
DOCKERCOMPOSEEXPLORERBACKENDDB := backend-db
DOCKERCOMPOSEEXPLORERFRONTEND := frontend
DOCKERCOMPOSEEXPLORERPROXY := proxy
DOCKERCOMPOSEEXPLORERSMARTCONTRACTVERIFIER := smart-contract-verifier
DOCKERCOMPOSEEXPLORERVISUALIZER := visualizer
DOCKERCOMPOSEEXPLORERSIGPROVIDER := sig-provider
DOCKERCOMPOSEEXPLORERVISUALIZERPROXY := visualizer-proxy
DOCKERCOMPOSEEXPLORERSTATSDB := stats-db
DOCKERCOMPOSEEXPLORERSTATS := stats

RUNEXPLORERBACKEND := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEXPLORERBACKEND)
RUNEXPLORERBACKENDDB := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEXPLORERBACKENDDB)
RUNEXPLORERFRONTEND := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEXPLORERFRONTEND)
RUNEXPLORERPROXY := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEXPLORERPROXY)
RUNEXPLORERSMARTCONTRACTVERIFIER := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEXPLORERSMARTCONTRACTVERIFIER)
RUNEXPLORERVISUALIZER := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEXPLORERVISUALIZER)
RUNEXPLORERSIGPROVIDER := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEXPLORERSIGPROVIDER)
RUNEXPLORERVISUALIZERPROXY := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEXPLORERVISUALIZERPROXY)
RUNEXPLORERSTATSDB := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEXPLORERSTATSDB)
RUNEXPLORERSTATS := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEXPLORERSTATS)

STOPEXPLORERBACKEND := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSEEXPLORERBACKEND) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSEEXPLORERBACKEND)
STOPEXPLORERBACKENDDB := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSEEXPLORERBACKENDDB) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSEEXPLORERBACKENDDB)
STOPEXPLORERFRONTEND := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSEEXPLORERFRONTEND) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSEEXPLORERFRONTEND)
STOPEXPLORERPROXY := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSEEXPLORERPROXY) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSEEXPLORERPROXY)
STOPEXPLORERSMARTCONTRACTVERIFIER := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSEEXPLORERSMARTCONTRACTVERIFIER) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSEEXPLORERSMARTCONTRACTVERIFIER)
STOPEXPLORERVISUALIZER := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSEEXPLORERVISUALIZER) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSEEXPLORERVISUALIZER)
STOPEXPLORERSIGPROVIDER := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSEEXPLORERSIGPROVIDER) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSEEXPLORERSIGPROVIDER)
STOPEXPLORERVISUALIZERPROXY := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSEEXPLORERVISUALIZERPROXY) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSEEXPLORERVISUALIZERPROXY)
STOPEXPLORERSTATSDB := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSEEXPLORERSTATSDB) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSEEXPLORERSTATSDB)
STOPEXPLORERSTATS := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSEEXPLORERSTATS) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSEEXPLORERSTATS)

BACKENDDBDATAVOLUME := snapchain-tohma-block-explorer_backend_db_data
STATSDBDATAVOLUME := snapchain-tohma-block-explorer_stats_db_data

.PHONY: run-explorer
run-explorer: ## Runs all explorer services
	$(RUNEXPLORERBACKENDDB)
	$(RUNEXPLORERSTATSDB)
	sleep 5
	$(RUNEXPLORERBACKEND)
	$(RUNEXPLORERFRONTEND)
	$(RUNEXPLORERSTATS)
	$(RUNEXPLORERSMARTCONTRACTVERIFIER)
	$(RUNEXPLORERVISUALIZER)
	$(RUNEXPLORERSIGPROVIDER)
	$(RUNEXPLORERVISUALIZERPROXY)
	$(RUNEXPLORERPROXY)

.PHONY: stop-explorer
stop-explorer: ## Stops all explorer services
	$(STOPEXPLORERPROXY)
	$(STOPEXPLORERVISUALIZERPROXY)
	$(STOPEXPLORERSIGPROVIDER)
	$(STOPEXPLORERVISUALIZER)
	$(STOPEXPLORERSMARTCONTRACTVERIFIER)
	$(STOPEXPLORERSTATS)
	$(STOPEXPLORERFRONTEND)
	$(STOPEXPLORERBACKEND)
	$(STOPEXPLORERSTATSDB)
	$(STOPEXPLORERBACKENDDB)

.PHONY: run-explorer-db
run-explorer-db: ## Runs the explorer databases
	$(RUNEXPLORERBACKENDDB)
	$(RUNEXPLORERSTATSDB)

.PHONY: stop-explorer-db
stop-explorer-db: ## Stops the explorer databases
	$(STOPEXPLORERSTATSDB)
	$(STOPEXPLORERBACKENDDB)

.PHONY: remove-volumes
remove-volumes: ## Removes Docker volumes
	docker volume rm $(BACKENDDBDATAVOLUME) $(STATSDBDATAVOLUME)

.PHONY: logs
logs: ## Shows logs
	$(DOCKERCOMPOSE) logs -f

.PHONY: restart-explorer
restart-explorer: stop-explorer remove-volumes run-explorer logs

.PHONY: ps
ps: ## Check all running services
	$(DOCKERCOMPOSE) ps --status running --format "table {{.Service}}\t{{.Image}}\t{{.Status}}"

.PHONY: ps-exited
ps-exited: ## Check all exited services
	$(DOCKERCOMPOSE) ps -a --format "table {{.Service}}\t{{.Image}}\t{{.Status}}" \
		| grep 'Exited' \
		|| echo "No exited containers"

.PHONY: help
help: ## Prints this help
		@grep -h -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| sort \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

.DEFAULT_GOAL := help